name: Build & Test

on:
  pull_request:
    branches: ["main"]

  # Allow other workflows to call this one (i.e. from deploy.yml)
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install pnpm
      - uses: pnpm/action-setup@v4

      # Use Node.js 22
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: "pnpm"

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run linter
      - name: Run linter
        run: pnpm lint

      # Run prettier check
      - name: Run prettier
        run: pnpm format:check

      # Build the project
      - name: Build
        run: pnpm build
